### ISSUE TITLE
Pidgin tray icon not updating

### ISSUE THREAD

**Issue by willbprog127** [bbidulock/icewm#382]
On IceWM 1.6.1, the Pidgin tray icon does not update although this is not a problem in other window managers / desktop environments.  

If you start Pidgin offline, then go online, the Pidgin tray icon still displays as offline.  Also, when the 'Blink on new messages' is enabled, the Pidgin tray icon does not blink...it still displays the offline icon.

* IceWM 1.6.1
* antiX 19 Linux (Debian-based) - amd64
* Radeon HD 2600 XT video card

Thanks! :+1:

**Comment by willbprog127** [comment]
I have found that if you restart IceWM from the menu, the Pidgin tray icon begins to update, so it appears it doesn't update from first IceWM startup, but restarting through the menu temporarily 'fixes' it.

**Comment by gijsbers** [comment]
Hi! Does it matter if pidgin plugins are active or does this also happen without plugins?
Which versions of pidgin? Can you find a similar problem with other systray icons?

**Comment by willbprog127** [comment]
> Hi! Does it matter if pidgin plugins are active or does this also happen without plugins?
> Which versions of pidgin? Can you find a similar problem with other systray icons?

It does not matter if Pidgin plugins are active or not, this issue happens either way.  The installed version of Pidgin is "Pidgin 2.13.0 (libpurple 2.13.0)".  Again, the Pidgin tray icon works fine in Fluxbox, Xfce4 and others, just not on IceWM until you do a 'Restart IceWM' from the menu.

I don't have other tray icons that change as often as Pidgin, so I haven't seen anything from other apps.

Thanks! :smile:

**Comment by gijsbers** [comment]
I get this when I start Pidgin.
![p3](https://user-images.githubusercontent.com/4169687/64564524-04a1c380-d352-11e9-9619-bed5f429fa77.png)
Is that what you get? Or what do you get and what should it look like?
How can I test some messages with you?

**Comment by willbprog127** [comment]
> I get this when I start Pidgin.
> ![p3](https://user-images.githubusercontent.com/4169687/64564524-04a1c380-d352-11e9-9619-bed5f429fa77.png)
> Is that what you get? Or what do you get and what should it look like?
> How can I test some messages with you?

When you start Pidgin, are you starting it automatically with 'Available' status?  I start with 'Offline', then manually set the status to 'Available'.  Can you test like that?

Thanks :+1:

**Comment by gijsbers** [comment]
Ah that is it. I can now reproduce your scenario. Thanks for your patience. :)

**Comment by willbprog127** [comment]
> Thanks for your patience. :)

Thank *you*!  I appreciate you looking into this. :smile:

**Comment by gijsbers** [comment]
I looked at the communication and it looks like Pidgin is confused about the protocols.
Unfortunely in the Pidgin source I can't find the lines where they do this stuff,
so it remains unclear to me what they want or how to circumvent their mistakes.

**Comment by willbprog127** [comment]
> I can't find the lines where they do this stuff, so it remains unclear to me 
> what they want or how to circumvent their mistakes.

Thanks for trying.  Something *does* get corrected with IceWM is restarted through the menu, but who knows what it is.  The Pidgin devs seem a bit unapproachable, otherwise I'd confer with them about this.

Thanks anyway! 😄

**Comment by willbprog127** [comment]
Just further info.  I have been running the ancient IceWM version 1.3.8 provided with FreeBSD and the Pidgin icon in the system tray works properly.  

While I haven't had the chance to conduct heavy research, something changed from the 'old days' in the tray's code that now causes this problem.  Also, when you restart the latest IceWM through the menu, the tray then starts working properly.

**Comment by gijsbers** [comment]
Yes, that is possible. 1.3.8 used an external tray, which we no longer support. But in principle you could configure icewm to use an external tray and then copy the old 1.3.8 tray into the bin directory and let icewm-session start that for you.

Once an icon is show in the internal tray the application is free to do as it pleases with it and it can show whatever it wants. It is just a 24 by 24 window. So icewm poses no restriction there.

**Comment by DieSpinne** [comment]
I do not have Pidgin, but give `alltray` a try. It worked with other "updatable" icons for me.

**Comment by Vrihub** [comment]
> I have found that if you restart IceWM from the menu, the Pidgin tray icon begins to update, so it appears it doesn't update from first IceWM startup, but restarting through the menu temporarily 'fixes' it.

FYI this is still happening on
icewm 3.6.0-1.1
pidgin 2.14.14-1
(Debian Trixie/testing packages)

Steps to reproduce:
- Start pidgin in "offline" mode, "offline" icon in tray
- Go online, icon stays "offline"
- Restart icewm from the menu, now the tray icon starts working as expected

**Comment by gijsbers** [comment]
I remember that this is a bug in Pidgin that couldn't be fixed because Pidgin is no longer maintained.
