### ISSUE TITLE
Two bugs in icesh addWorkspace

### ISSUE THREAD

**Issue by Vrihub** [bbidulock/icewm#812]
A couple of bugs in `icesh addWorkspace` (I guess they are closely related so maybe one issue is enough)

### 1. Name of new workspace not appearing on taskbar

Steps to reproduce:
1. `icesh addWorkspace new`

Expected result: the "new" name should appear everywhere the workspace is listed.

Actual result: the new workspace box on the taskbar has the workspace number instead of the "new" name. You must enter the workspace to have the "new" name correctly displayed.
All the other places correctly display the new name: windowlist, popup tip when mouse-hovering on the new workspace box in the taskbar, "Move to" window menu commmand)

### 2. Restarting icewm and re-adding a new workspace reuses the name used in the previous session

Steps to reproduce:
1. Reproduce the previous bug above
2. Restart icewm from the menu, the number of workspaces shrinks back to the default
3. Add another workspace: `icesh addWorkspace newest`

Expected result: the "newest" workspace should appear

Actual result: the "new" workspace appears, i.e. the name for the new workspace used in the previous icewm session is wrongly reused. Besides, `icesh` gives the following error messages:
```
free(): invalid pointer
Aborted
```

**Comment by gijsbers** [comment]
2. was easy to fix.

**Comment by gijsbers** [comment]
Done.

**Comment by Vrihub** [comment]
Thanks. I confirm bug 2. is fixed: new workspaces created after restart get the new correct name, and now icewm remembers previously added workspaces after the restart. This seems more correct in general (a little drawback: we now don't have a way to delete "extra" workspaces, at least until `icesh delWorkspace` is implemented).

Bug 1 still happens for me, though. :(

**Comment by gijsbers** [comment]
you may not have updated your icesh.

you can delete workspaces, just consult the documentation.

**Comment by Vrihub** [comment]
> you may not have updated your icesh.

I ran `make clean ; make ; make install` (should I also `make distclean` and generate a new `configure`?), and indeed I could test that bug 2. is fixed. But I keep getting new workspaces showing the workspace number on the taskbar, until I visit them and then the workspace name appears.

> you can delete workspaces, just consult the documentation.

Ah you mean `icesh workspaces n`, I kind of assumed that, given the absence of `icesh delWorkspace`, the number of workspaces could only be increased, not reduced. That's nice.

**Comment by Vrihub** [comment]
I discovered another little bug (I think related to bug 1. above, which is still happening even with the latest git, BTW), this time when renaming a workspace.

Steps to reproduce:
1. Rename a workspace
2. Go to some window in another workspace, open the window menu, select "Move To"

Expected result: in the "Move To" list, the renamed workspace should show the new name

Actual result: the old workspace name is shown.

This happens both when renaming one of the default workspaces, or a new workspace added with icesh, and both with old windows (already existing when the workspace has been renamed) and with new windows (created after the rename).

**Comment by gijsbers** [comment]
This fixes it for me.

**Comment by Vrihub** [comment]
> This fixes it for me.

I confirm it fixes all bugs reported in this issue! Thank you very much!
